# Generated by Django 5.0.6 on 2024-06-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_conversation_conversationmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='modified_at',
        ),
    ]
